#!/bin/sh

savesdir="${HOME}/.local/share/zork2/SAVE"
z3file="/usr/share/zork2/ZORKII"

# make saves directory if it does not exist yet
mkdir -p -- "${savesdir}"

# start frotz
frotz -R "${savesdir}" "${z3file}"

